### ISSUE TITLE
Download-Statistik hinzufügen

### ISSUE THREAD

**Issue by Gerome100** [PCJones/usenet-guide#3]
Hallo,

wäre es möglich, dass Sie ihre Download-Statistik hinzufügen, damit man sehen kann, woher die meisten Grabs kommen? So wie hier:

https://www.reddit.com/r/usenet/comments/17my7ab/comment/k7olueq/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

https://i.epvpimg.com/Tyy1dab.png
![Tyy1dab](https://github.com/user-attachments/assets/790ddd1b-fb45-486d-a7d2-75faf5d38dd0)

**Comment by PCJones** [comment]
Hi,

sprichst du deutsch? Ich frage nur, weil du mich Siezt :-)

Der Beitrag auf reddit ist von mir. So sind meine letzten 30 Tage:
![grafik](https://github.com/user-attachments/assets/ac3f5ab7-0084-4dc5-9489-d36e38c6275c)

Das ist allerdings etwas verzerrt, da ich releases zuerst in Englisch lade, und dann, sobald es sie als German DL release gibt, ersetze. Dadurch habe ich z.B. auch bei NZBGeek viele Downloads. Würde ich nur Deutsch (bzw German DL) laden, hätten die internationalen Indexer deutlich weniger Grabs.

**Comment by Gerome100** [comment]
Hi,

ja ich spreche deutsch. Wollte nur freundlich sein, wenn ich schon Anforderungen stelle. 😄 Also verstehe ich das richtig, dass es nicht wirklich viel Sinn macht, deine Stats hier hochzuladen?

**Comment by Gerome100** [comment]
Alles klar, check. Ich werd' mal auf den Discord hüpfen. Generell suche ich viel Anime Content und hab aktuell die meisten Grabs von SceneNZBs. Ich bin auch vergeblich nach nem DrunkenSlug Invite am schauen, aber kriege leider keinen. BTW ich hab mal auf Reddit gelesen, dass auf AnimeTosho wohl CP verbreitet wurde, kann man sich irgendwie dagegen schützen?

**Comment by PCJones** [comment]
Die gleichen Fragen gleich gerne im Discord :P

**Comment by IPeTeXI** [comment]
https://discord.gg/jqkcMHH22T
